### ISSUE TITLE
tests and benchmark not working

### ISSUE THREAD

**Issue by Bubu** [chomechome/charamel#7]
I wanted to package this for archlinux but somehow most of the tests are failling and the benchmark script immediately bails out with the following error:

```
poetry run python scripts/benchmark.py
Traceback (most recent call last):
  File "scripts/benchmark.py", line 62, in <module>
    CHARAMEL: charamel.Detector().detect,
  File "/home/bubu/tmp/charamel/charamel/detector.py", line 66, in __init__
    self._features = load_features()
  File "/home/bubu/tmp/charamel/charamel/resources/__init__.py", line 40, in load_features
    features = _unpack(RESOURCE_DIRECTORY / 'features.gzip', pattern='>H')
  File "/home/bubu/tmp/charamel/charamel/resources/__init__.py", line 30, in _unpack
    return [values[0] for values in struct.iter_unpack(pattern, data.read())]
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')
make: *** [Makefile:28: benchmark] Error 1
```

This is from a poetry env so not using any system python packages I believe.

Mh, it also fails in basic usage mentioned in the readme.

**Comment by chomechome** [comment]
Since model weight files are rather large, they're stored under [Git LFS](https://git-lfs.github.com/). Probably, you don't have it installed and thus Git did not clone them. Can you try installing LFS and then running `git lfs pull`?

**Comment by Bubu** [comment]
Thanks, that was indeed the problem. Instead of doing the git-lfs checkout, I now do use the pypi package. (Which unfortunately means I cannot run the tests during packaging as they are not included there.)

**Comment by chomechome** [comment]
I see, well, adding the tests to the package would do more harm than good as they use around 6 MB of files in different encodings (also stored under LFS).
