### ISSUE TITLE
Converting application to EXE with PyInstaller errors

### ISSUE THREAD

**Issue by ricky-davis** [chomechome/charamel#8]
Hello, 
When I try to convert my application into an EXE with PyInstaller, I'm able to build the EXE, but when I run it, it throws an error that it cannot find the features.gzip file.
I believe the fix would be to include it as a required file in the setup.py or build hooks into the package (https://pyinstaller.readthedocs.io/en/stable/hooks.html?highlight=hooks#providing-pyinstaller-hooks-with-your-package)

Here's the full error I'm getting:
![image](https://user-images.githubusercontent.com/48695279/96190814-71e63780-0f08-11eb-9f30-287f7feca4fa.png)

I've attempted to fix this myself but I don't have the best understanding on how Python Packages work, nor how charamel works. 

If you can fix this I'd be extremely grateful. Charamel works flawlessly when I run the python directly, and I'd love to be able to continue using it.

**Comment by chomechome** [comment]
Hi, could you list the commands you run so that I can reproduce the issue? 

I had a quick look at PyInstaller docs and I think the solution is covered in [this section](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#analysis-finding-the-files-your-program-needs):
> If your program depends on access to certain data files, you can tell PyInstaller to include them in the bundle as well. You do this by modifying the spec file, an advanced topic that is covered under Using Spec Files.

**Comment by ricky-davis** [comment]
My build script is:
![image](https://user-images.githubusercontent.com/48695279/96358610-bcb1ac00-10ce-11eb-96e5-43c19077ef28.png)

There *is* a way to get it working with the spec file, but I haven't been able to figure it out. The hooks essentially modify the spec file automatically, instead of having to manually do it every time you build the application.


I haven't been able to get the spec file to include non-python files, the only way I can think is by including the files needed in my source code and using --add-data to point to them, as I can't access them through the module

**Comment by chomechome** [comment]
Data files should be supplied using parameter `datas` in the spec file `Analysis` call ([reference](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#spec-file-operation)), they mention that it's kinda the same as using `--add-data`. Archives from the [resources folder](https://github.com/chomechome/charamel/tree/master/charamel/resources) are missing from `charamel` so this is what we need to add there. Normally, you can find them under `site-packages/charamel/resources` folder of your Python interpreter but I'm not sure that this is where packages are installed on Windows.

I had a look at PyInstaller hook examples and [this is the hook](https://github.com/pyinstaller/hooksample/blob/master/src/pyi_hooksample/__pyinstaller/hook-pyi_hooksample.py#L31-L50) that likely can modify `datas` automatically to include required files. I haven't had time to try it though.
